FROM oven/bun:canary AS base
WORKDIR /app

# Copy .env file stage
FROM base AS envcopy
WORKDIR /app
# Copy if exists otherwise create during build
COPY .env.development .env.development

# Install dependencies stage
FROM base AS deps
COPY package.json bun.lockb* ./
RUN bun install --frozen-lockfile

# Build stage
FROM base AS build
COPY package.json bun.lockb* ./
RUN bun install --frozen-lockfile
COPY . .

# Development stage
FROM base AS development
WORKDIR /app


# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app .
COPY --from=envcopy /app/.env.development .env.development

RUN bun --env-file=.env.development ./utility/create-config.ts

EXPOSE 8080 9999

CMD ["bun", "run", "development"]