services:
  frostfire-gateway-prod:
    build:
      context: ../../
      dockerfile: src/docker/Dockerfile.prod
    container_name: frostfire-gateway-prod
    restart: always
    network_mode: "host"
    env_file:
      - ../../.env.production
    volumes:
      - ../../src/certs:/app/certs:ro
      - ../../src/logs:/app/logs
      - ../../config:/app/config
