version: '3.8'

services:
  mysql-dev:
    image: mysql:9.0
    container_name: frostfire-mysql-dev
    restart: unless-stopped
    command: --max-connections=500
    environment:
      # Not meant to be secret
      MYSQL_ROOT_PASSWORD: frostfire_forge_development
      MYSQL_DATABASE: frostfire_forge_development
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql-data-dev:/var/lib/mysql
    networks:
      - frostfire-network-dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  gateway-dev:
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile.dev
    container_name: frostfire-gateway-dev
    restart: unless-stopped
    depends_on:
      mysql-dev:
        condition: service_healthy
    ports:
      - "80:80"
      - "9999:9999"
    environment:
      DATABASE_HOST: mysql-dev
      DATABASE_PORT: 3306
    env_file:
      - ../../.env.development
    networks:
      - frostfire-network-dev

volumes:
  mysql-data-dev:
    driver: local

networks:
  frostfire-network-dev:
    driver: bridge
