version: '3.8'

services:
  gateway-dev:
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile.dev
    container_name: frostfire-gateway-dev
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "9999:9999"
      - "9443:9443"
    env_file:
      - ../../.env.development
    networks:
      - gateway-network-dev

networks:
  gateway-network-dev:
    driver: bridge
