FROM oven/bun:canary AS base
WORKDIR /app

# Install dependencies
FROM base AS deps
COPY package.json bun.lockb* ./
RUN bun install --frozen-lockfile

# Development stage
FROM base AS development
COPY --from=deps /app/node_modules ./node_modules
COPY . .

EXPOSE 80 443 9999 9443

CMD ["bun", "run", "development"]
