export const config = {
    WEBSOCKET_URL: '__VAR.WEBSOCKETURL__',
    WEB_SOCKET_PORT: '__VAR.WEB_SOCKET_PORT__',
    GATEWAY_WS_PORT: '__VAR.GATEWAY_WS_PORT__',
    VERSION: '__VAR.VERSION__',
    GATEWAY_ENABLED: '__VAR.GATEWAY_ENABLED__',
    GATEWAY_URL: '__VAR.GATEWAY_URL__'
};